import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  background: {
    position: 'absolute',
    width: width,
    height: height,
    top: 0,
    left: 0,
  },
  gradientLayer: {
    position: 'absolute',
    width: '100%',
    height: '40%',
    top: 0,
    opacity: 0.1,
  },
  inner: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingBottom: 40,
    paddingTop: 20,
  },
  header: {
    alignItems: 'center',
    marginBottom: 48,
    position: 'relative',
    marginTop: 30,
  },
  logoContainer: {
    width: 140,
    height: 140,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#10518b',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  title: {
    fontSize: 42,
    fontWeight: '900',
    textAlign: 'center',
    color: '#10518b',
    marginBottom: 8,
    letterSpacing: -0.8,
    textShadowColor: 'rgba(16, 81, 139, 0.2)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 18,
    textAlign: 'center',
    color: '#64748b',
    lineHeight: 24,
    fontWeight: '500',
  },
  formContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 32,
    padding: 32,
    shadowColor: '#10518b',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.2,
    shadowRadius: 30,
    elevation: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    backdropFilter: 'blur(10px)',
  },
  inputContainer: {
    marginBottom: 28,
    position: 'relative',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#343433',
    marginBottom: 12,
    letterSpacing: -0.3,
    paddingLeft: 8,
  },
  inputIconContainer: {
    position: 'absolute',
    left: 20,
    top: 55,
    zIndex: 1,
  },
  input: {
    borderWidth: 2,
    borderColor: 'rgba(226, 232, 240, 0.8)',
    padding: 20,
    paddingLeft: 60,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    fontSize: 17,
    color: '#1e293b',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 5,
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: '#5faeee',
    backgroundColor: '#ffffff',
    shadowColor: '#5faeee',
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
    transform: [{ scale: 1.01 }],
  },
  button: {
    backgroundColor: 'linear-gradient(135deg, #5faeee 0%, #10518b 100%)',
    padding: 22,
    borderRadius: 18,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#10518b',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
    overflow: 'hidden',
    position: 'relative',
  },
  buttonGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  buttonDisabled: {
    backgroundColor: '#cbd5e1',
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonShine: {
    position: 'absolute',
    top: -50,
    left: -50,
    width: 100,
    height: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    transform: [{ rotate: '30deg' }],
  },
  demoContainer: {
    marginTop: 32,
    padding: 24,
    backgroundColor: 'rgba(16, 81, 139, 0.05)',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(16, 81, 139, 0.1)',
    borderStyle: 'dashed',
  },
  demoTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#10518b',
    marginBottom: 12,
    textAlign: 'center',
  },
  demoText: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 6,
    lineHeight: 20,
    textAlign: 'center',
  },
  registerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 32,
    paddingTop: 24,
    borderTopWidth: 2,
    borderTopColor: 'rgba(226, 232, 240, 0.5)',
  },
  registerText: {
    color: '#64748b',
    fontSize: 16,
    fontWeight: '500',
  },
  registerLink: {
    color: '#10518b',
    fontWeight: '800',
    fontSize: 16,
    marginLeft: 8,
    textDecorationLine: 'none',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(16, 81, 139, 0.1)',
    overflow: 'hidden',
  },
  floatingElements: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  floatingShape1: {
    position: 'absolute',
    width: 150,
    height: 150,
    borderRadius: 40,
    backgroundColor: 'rgba(95, 174, 238, 0.1)',
    top: '10%',
    left: -50,
    transform: [{ rotate: '45deg' }],
  },
  floatingShape2: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 30,
    backgroundColor: 'rgba(16, 81, 139, 0.08)',
    bottom: '15%',
    right: -40,
    transform: [{ rotate: '-30deg' }],
  },

  eyeIconContainer: {
    position: 'absolute',
    right: 20,
    top: 55,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
});