import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  background: {
    position: 'absolute',
    width: width,
    height: height,
    top: 0,
    left: 0,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 30,
  },
  inner: {
    flex: 1,
    paddingHorizontal: 28,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    position: 'relative',
  },
  logoContainer: {
    width: 90,
    height: 90,
    borderRadius: 22,
    backgroundColor: '#10518b',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#10518b',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
    transform: [{ rotate: '45deg' }],
  },
  logoInner: {
    width: 60,
    height: 60,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '-45deg' }],
  },
  logoText: {
    fontSize: 26,
    fontWeight: '900',
    color: '#ffffff',
    transform: [{ rotate: '-45deg' }],
  },
  title: {
    fontSize: 38,
    fontWeight: '900',
    textAlign: 'center',
    color: '#10518b',
    marginBottom: 6,
    letterSpacing: -0.8,
    textShadowColor: 'rgba(16, 81, 139, 0.15)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  subtitle: {
    fontSize: 16,
    textAlign: 'center',
    color: '#64748b',
    lineHeight: 22,
    fontWeight: '500',
    maxWidth: '80%',
  },
  formContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 28,
    padding: 28,
    shadowColor: '#10518b',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 30,
  },
  sectionTitle: {
    marginBottom: 20,
    marginTop: 10,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(16, 81, 139, 0.1)',
  },
  sectionLabel: {
    fontSize: 20,
    fontWeight: '800',
    color: '#10518b',
    letterSpacing: -0.3,
    textTransform: 'uppercase',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    gap: 15,
  },
  halfInput: {
    flex: 1,
  },
  inputContainer: {
    marginBottom: 22,
    position: 'relative',
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#343433',
    marginBottom: 10,
    letterSpacing: -0.2,
    paddingLeft: 8,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  requiredStar: {
    color: '#ef4444',
    marginLeft: 2,
  },
  inputIconContainer: {
    position: 'absolute',
    left: 18,
    top: 52,
    zIndex: 1,
  },
  input: {
    borderWidth: 2,
    borderColor: 'rgba(226, 232, 240, 0.8)',
    padding: 18,
    paddingLeft: 55,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    fontSize: 16,
    color: '#1e293b',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 4,
    fontWeight: '500',
  },
  inputFocused: {
    borderColor: '#5faeee',
    backgroundColor: '#ffffff',
    shadowColor: '#5faeee',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
    transform: [{ scale: 1.01 }],
  },
  inputValid: {
    borderColor: 'rgba(34, 197, 94, 0.5)',
    backgroundColor: 'rgba(34, 197, 94, 0.03)',
  },
  inputError: {
    borderColor: 'rgba(239, 68, 68, 0.5)',
    backgroundColor: 'rgba(239, 68, 68, 0.03)',
  },
  errorText: {
    fontSize: 13,
    color: '#ef4444',
    marginTop: 6,
    marginLeft: 8,
    fontWeight: '500',
  },
  passwordRequirements: {
    backgroundColor: 'rgba(16, 81, 139, 0.04)',
    borderRadius: 14,
    padding: 18,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(16, 81, 139, 0.1)',
  },
  requirementsTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#10518b',
    marginBottom: 10,
  },
  requirementText: {
    fontSize: 14,
    marginBottom: 6,
    lineHeight: 20,
    fontWeight: '500',
  },
  requirementMet: {
    color: '#16a34a',
  },
  requirementUnmet: {
    color: '#64748b',
  },
  button: {
    backgroundColor: '#5faeee',
    padding: 22,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#10518b',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
    overflow: 'hidden',
    position: 'relative',
    marginTop: 10,
  },
  buttonGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  buttonDisabled: {
    backgroundColor: '#cbd5e1',
    shadowOpacity: 0,
    elevation: 0,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  buttonShine: {
    position: 'absolute',
    top: -50,
    left: -50,
    width: 100,
    height: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    transform: [{ rotate: '30deg' }],
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 28,
    paddingTop: 24,
    borderTopWidth: 2,
    borderTopColor: 'rgba(226, 232, 240, 0.5)',
  },
  loginText: {
    color: '#64748b',
    fontSize: 15,
    fontWeight: '500',
  },
  loginLink: {
    color: '#10518b',
    fontWeight: '800',
    fontSize: 15,
    marginLeft: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(16, 81, 139, 0.1)',
    overflow: 'hidden',
  },
  floatingElements: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  floatingShape1: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 35,
    backgroundColor: 'rgba(95, 174, 238, 0.08)',
    top: '15%',
    right: -40,
    transform: [{ rotate: '-25deg' }],
  },
  floatingShape2: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 30,
    backgroundColor: 'rgba(16, 81, 139, 0.06)',
    bottom: '20%',
    left: -30,
    transform: [{ rotate: '45deg' }],
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
    paddingHorizontal: 10,
  },
  progressStep: {
    flex: 1,
    height: 6,
    backgroundColor: 'rgba(226, 232, 240, 0.8)',
    borderRadius: 3,
    marginHorizontal: 2,
  },
  progressStepActive: {
    backgroundColor: '#5faeee',
  },
  progressStepCompleted: {
    backgroundColor: '#10518b',
  },
  stepIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: -9,
    zIndex: 2,
  },
  stepIndicatorActive: {
    backgroundColor: '#5faeee',
  },
  stepIndicatorCompleted: {
    backgroundColor: '#10518b',
  },
  stepNumber: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },

  eyeIconContainer: {
    position: 'absolute',
    right: 18,
    top: 52,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
});